# Generated by Django 2.2.4 on 2019-12-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalorieMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateTimeField()),
                ('calories', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateTimeField()),
                ('intensity', models.CharField(choices=[('Light', 'Light'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=100)),
                ('length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MuscleMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateTimeField()),
                ('left_bicep', models.FloatField()),
                ('right_bicep', models.FloatField()),
                ('left_thigh', models.FloatField()),
                ('right_thigh', models.FloatField()),
                ('waist', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WeightMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateTimeField()),
                ('weight', models.FloatField()),
            ],
        ),
    ]
