# Generated by Django 2.2.2 on 2019-07-03 00:15

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', unique_with=('title',)),
            preserve_default=False,
        ),
    ]
