# Generated by Django 2.2.2 on 2019-07-03 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_post_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Project',
        ),
    ]
