# Generated by Django 2.2.3 on 2019-07-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190703_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='homeurl',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
