# Generated by Django 2.2.3 on 2019-07-11 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190711_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='homeurl',
            field=models.URLField(blank=True),
        ),
    ]
