# Generated by Django 2.2.3 on 2019-07-09 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='link',
            new_name='homeurl',
        ),
    ]
