# Generated by Django 2.2.2 on 2019-07-03 00:12

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('now', '0002_auto_20190629_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', unique_with=('title',)),
            preserve_default=False,
        ),
    ]
