# Generated by Django 2.2.2 on 2019-07-03 00:26

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('now', '0004_auto_20190703_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='now',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=('title',)),
        ),
    ]
