# Generated by Django 2.2.3 on 2019-07-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Currently Reading', 'Currently Reading'), ('To Read', 'To Read'), ('Pause', 'Pause')], default='To Read', max_length=20),
        ),
    ]
