# Generated by Django 2.2.3 on 2019-07-24 02:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190723_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_read',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
