# Generated by Django 2.2.4 on 2019-08-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20190724_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
