# Generated by Django 2.2.4 on 2019-08-20 12:36

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_toRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('buylink', models.URLField(blank=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=True, populate_from='title', unique_with=('title',))),
                ('description', models.TextField(blank=True)),
                ('cover', models.ImageField(upload_to='book-cover/')),
            ],
        ),
    ]
