# Generated by Django 2.2.4 on 2019-11-22 20:16

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_intro_thoughts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='intro_thoughts',
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title', unique_with=('title',)),
        ),
    ]
