# Generated by Django 2.2.4 on 2019-11-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20191122_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='main_category',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
