# Generated by Django 2.2.4 on 2019-12-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_main_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='draft',
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('READ', 'READ'), ('TO READ', 'TO READ'), ('READING', 'READING')], default='TO READ', max_length=100),
        ),
    ]
