# Generated by Django 2.2.4 on 2019-12-26 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20191226_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rank',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
