# Generated by Django 2.2.4 on 2019-12-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20191226_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_read',
            field=models.DateField(blank=True, null=True),
        ),
    ]
