# Generated by Django 2.2.4 on 2019-12-26 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_book_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='short_description',
        ),
    ]
