# Generated by Django 2.2.3 on 2019-08-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='category',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
