# Generated by Django 2.2.4 on 2019-08-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiltw', '0005_auto_20190711_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiltw',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
