# Generated by Django 2.2.3 on 2019-07-12 03:07

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=('title',))),
                ('body', models.TextField()),
                ('cover', models.ImageField(upload_to='post-images/')),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=200)),
            ],
        ),
    ]
