# Generated by Django 2.2.3 on 2019-07-12 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, upload_to='post-images/'),
        ),
    ]
