# Generated by Django 2.2.3 on 2019-08-07 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writings', '0002_auto_20190712_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
