# Generated by Django 2.2.4 on 2019-10-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writings', '0007_auto_20190920_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Coding', 'Coding'), ('Cooking', 'Cooking'), ('Personal', 'Personal')], default='Personal', max_length=20),
        ),
    ]
