# Generated by Django 2.2.4 on 2019-11-10 16:30

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writings', '0008_auto_20191003_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title', unique_with=('title',)),
        ),
    ]
