# Generated by Django 2.2.4 on 2019-12-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writings', '0014_remove_comment_approved_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
