# Generated by Django 2.2.4 on 2020-01-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writings', '0015_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='main-post-images/'),
        ),
    ]
