# Generated by Django 2.2.4 on 2020-01-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writings', '0016_post_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='allow_incoming_webmentions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='allow_outgoing_webmentions',
            field=models.BooleanField(default=False),
        ),
    ]
