# Generated by Django 2.2.9 on 2020-02-13 21:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writings', '0018_auto_20200123_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('author', models.CharField(max_length=200)),
                ('date_read', models.DateField(blank=True, null=True)),
                ('date_published', models.DateField(auto_now_add=True)),
                ('cover', models.ImageField(blank=True, upload_to='book-cover/')),
                ('status', models.CharField(choices=[('READ', 'READ'), ('TO READ', 'TO READ'), ('READING', 'READING')], default='TO READ', max_length=100)),
                ('main_category', models.CharField(blank=True, max_length=200)),
                ('buylink', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('rank', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
