# Generated by Django 2.2.10 on 2020-02-23 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writings', '0019_auto_20200213_1651'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
