# Generated by Django 2.2.10 on 2020-03-20 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writings', '0020_delete_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='allow_incoming_webmentions',
        ),
        migrations.RemoveField(
            model_name='post',
            name='allow_outgoing_webmentions',
        ),
    ]
