# Generated by Django 2.2.4 on 2019-12-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisemeasurement',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
